name: Bot Discord Build and Test

on:
  push:
    branches:
      dev
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Dependencies
      working-directory: ./garm
      run: npm install

    - name: Build and Start Discord Bot
      working-directory: ./garm
      run: |
        npm run build
        node index.js